[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime_guess = "2.0.5"
dirs = "5.0.1"
url-escape = "0.1.1"
infer = "0.16.0"
walkdir = "2.5.0"
